---
drake_cache: ".ui"
dependencies: "dependencies"
output:
  html_tag:
    filename: "index.html"
    dirpath: "`r library(econR);'~/Documents/GitHub/covid19/docs'`"
    object: "ui"
---


```{r makecondition}
library(dplyr)
library(shiny)
library(htmltools)
library(econR)
library(readr)
library(leaflet)
library(plotly)
library(shinymaterial)


```

```{r dependencies}
dependencies <- {
  myown_deps <- htmltools::htmlDependency(
      name="myown",
      version="1.0.0",
      src=c(file= . %//% "assets"),
      script = "js/myscript.js",
      stylesheet="css/mystyle.css"
    )
  econR_deps <- econR::html_dependencies()
  tagList(
    econR_deps$jquery(),
    econR_deps$materialise(),
    myown_deps
  )
}
```



## =======================

### Input

```{r input_pickDate}
input_pickDate <- sliderInput("pickDate",
                                   "疫情爆發天數",
                        min = as.Date("2021-04-01"),
                        max = as.Date("2021-06-24"),
                        value = as.Date("2021-04-01"),
                        timeFormat = "%F")

```

### Output

```{r output_ntp}
output_ntp <- plotly::plotlyOutput("ntp")
```




## =======================

### UI

```{r ui}
ui <- tags$body(
  fluidPage(

    # Application title
    titlePanel("新北市確診分佈"),

    # Sidebar with a slider input for number of bins 
    sidebarLayout(
      position = "right",
      sidebarPanel(input_pickDate),
    # Show a plot of the generated distribution
      mainPanel(output_ntp)
    
)))
```



## =======================


## Browse

```{r}
web$browse()
```





## JS


<!--JS end-->
